apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dev
  labels:
    app: nginx
    environment: dev
    team: platform
    managed-by: terraform
data:
  default.conf: |
        server {
            listen 80;

            location = /health {
                root /tmp;
            }

            location = /hello {
                root /tmp;
            }

            location / {
                return 404;
            }
        }
