apiVersion: v1
kind: Pod
metadata:
  labels:
    app: static-nginx
  name: static-nginx
spec:
  containers:
  - image: nginx
    name: static-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
