apiVersion: v1
kind: Pod
metadata:
  labels:
    app: static-nginx
  name: static-nginx
spec:
  containers:
  - image: nginxinc/nginx-unprivileged@sha256:cb92301e719d6639028de775fe8b28e15f58343aca5e5372001311958aafb300
    name: static-nginx
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 101
      capabilities:
        drop:
          - ALL
    livenessProbe:
      exec:
        command:
          - pgrep
          - "[n]ginx"
    resources:
      requests:
        cpu: 10m
        memory: 4Mi
      limits:
        cpu: 50m
        memory: 10Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
