# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: staging
  labels:
    app: nginx
    environment: staging
    team: platform
    managed-by: terraform
spec:
  selector:
    app: nginx
    environment: staging
    track: "blue"
  type: ClusterIP
  ports:
  - name: nginx-http
    protocol: TCP
    port: 8080
    targetPort: 80
  publishNotReadyAddresses: false
---


