apiVersion: v1
kind: ResourceQuota
metadata:
  name: tools-ressources
  namespace: tools
spec:
  hard:
    requests.cpu: "150m"
    requests.memory: "96Mi"
    limits.cpu: "300m"
    limits.memory: "192Mi"
    pods: 4
