apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-ressources
  namespace: dev
spec:
  hard:
    requests.cpu: "800m"
    requests.memory: "256Mi"
    limits.cpu: "2000m"
    limits.memory: "512Mi"
    pods: 10
    services: 4
    count/deployment.apps: 4
