apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-ressources
  namespace: prod
spec:
  hard:
    requests.cpu: "1512m"
    requests.memory: "161Mi"
    limits.cpu: "1512m"
    limits.memory: "161Mi"
    pods: 7
    services: 2
    count/deployment.apps: 2
