apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-ressources
  namespace: prod
spec:
  hard:
    requests.cpu: "242m"
    requests.memory: "30Mi"
    limits.cpu: "424m"
    limits.memory: "61Mi"
    pods: 7
    services: 2
    count/deployment.apps: 2
