apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-ressources
  namespace: prod
spec:
  hard:
    requests.cpu: "600m"
    requests.memory: "192Mi"
    limits.cpu: "2400m"
    limits.memory: "512Mi"
    pods: 8
    services: 2
    count/deployment.apps: 2
