apiVersion: v1
kind: ResourceQuota
metadata:
  name: stage-ressources
  namespace: staging
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "160Mi"
    limits.cpu: "2000m"
    limits.memory: "400Mi"
    pods: 7
    services: 2
    count/deployment.apps: 2
