apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-ressources
  namespace: dev
spec:
  hard:
    requests.cpu: "600m"
    requests.memory: "80Mi"
    limits.cpu: "1400m"
    limits.memory: "192Mi"
    pods: 7
    services: 1
    count/deployment.apps: 2
