apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tainted
  namespace: default
  labels:
    app: nginx-tainted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tainted
  template:
    metadata:
      labels:
        app: nginx-tainted
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/premium
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "taint-color"
          operator: "Equal"
          value: "yellow"
          effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
