apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels: 
    environment: dev
    team: platform
    managed-by: terraform
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    team: platform
    managed-by: terraform
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
    team: platform
    managed-by: terraform
---
apiVersion: v1
kind: Namespace
metadata:
  name: tools
  labels:
    environment: tools
    team: platform
    managed-by: terraform
---
