apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev
  name: nginx-config
  labels:
    app: nginx
    environment: dev
    team: platform
    managed-by: terraform
immutable: true
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      server {
        listen 80;

        location = /health {
            root /usr/share/nginx/html;
            try_files /index.html =404;
        }

        location = /hello {
            root /usr/share/nginx/html;
            try_files /index.html =404;
        }

        location /version {
            return 200 "$nginx_version";
            add_header Content-Type text/plain;
        }

        location / {
            root /usr/share/nginx/html;
            try_files /index.html =404;
        }

        location = /stub_status {
            stub_status;
        }

      }

      server {

        listen 443 ssl;

        ssl_certificate         /usr/share/nginx/certificates/tls.crt;
        ssl_certificate_key     /usr/share/nginx/certificates/tls.key;

        location = /health {
            root /usr/share/nginx/html;
            try_files /index.html =404;
        }

        location / {
            root /usr/share/nginx/html;
            try_files /index.html =404;
        }

        location = /stub_status {
            stub_status;
        }
      }
    }
