apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
    environment: dev
    team: platform
    managed-by: terraform
    version: "1.30.4"
    track: "stable"
spec:
  selector:
    matchLabels:
      app: nginx
      environment: dev
      track: "stable"
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: nginx
        prometheus.io/scrape: "true"
        prometheus.io/port: "8123"
      labels:
        app: nginx
        environment: dev
        track: "stable"
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 101
      priorityClassName: nginx
      initContainers:
        - name: html-file
          image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
          command:
            - sh
            - -c
            - echo "index-html-file" > /usr/share/nginx/html/index.html;
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      containers:
        - name: sidecar-nginx
          image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
          volumeMounts:
            - name: nginx-logs
              mountPath: /var/log/nginx
          command:
            - sh
            - -c
            - "while true; do if [ -s /var/log/nginx/access.log ]; then cat /var/log/nginx/access.log > /var/log/nginx/access.log-$(date +%Y%m%d-%H%M%S) && > /var/log/nginx/access.log; fi; if [ -s /var/log/nginx/error.log ]; then cat /var/log/nginx/error.log > /var/log/nginx/error.log-$(date +%Y%m%d-%H%M%S) && > /var/log/nginx/error.log; fi; sleep 2; done"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
        - name: nginx
          image: nginx@sha256:09cc2702709e6388d979d8030e3ab4eb1ceb699b2dced26d7543e872a822e823
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 15m
              memory: 5Mi
            limits:
              cpu: 50m
              memory: 10Mi
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /hello
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: html
              mountPath: /usr/share/nginx/html
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-certificates
              mountPath: /usr/share/nginx/certificates
            - name: nginx-logs
              mountPath: /var/log/nginx
        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter@sha256:85666e7fde7e253f1c6d978f9a961245df4c9cdb7677e1866d9bb28e8f9ee41d
          args:
            - "--nginx.scrape-uri=http://127.0.0.1:80/stub_status"
            - "--web.listen-address=:8123"
          resources:
            requests:
              cpu: 10m
              memory: 4Mi
            limits:
              cpu: 50m
              memory: 8Mi
          ports:
            - name: metrics
              containerPort: 8123
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: html
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-logs
          emptyDir: {}
        - name: nginx-certificates
          secret:
            secretName: nginx-secret
      restartPolicy: Always
---
