# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev
  labels:
    app: nginx-extended
    environment: dev
    team: platform
    managed-by: terraform
spec:
  selector:
    app: nginx-extended
  type: ClusterIP
  ports:
    - name: nginx-http
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: nginx-https
      port: 8443
      protocol: TCP
      targetPort: 443
  publishNotReadyAddresses: false
---
