apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limits
  namespace: prod
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 60m
      memory: 8Mi
    default:
      cpu: 120m
      memory: 15Mi
    min:
      cpu: 12m
      memory: 5Mi
    max:
      cpu: 180m
      memory: 20Mi
