apiVersion: v1
kind: LimitRange
metadata:
  name: staging-limits
  namespace: staging
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 55m
      memory: 7Mi
    default:
      cpu: 110m
      memory: 14Mi
    min:
      cpu: 12m
      memory: 5Mi
    max:
      cpu: 165m
      memory: 18Mi
