apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limits
  namespace: prod
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 61m
      memory: 8Mi
    default:
      cpu: 121m
      memory: 15Mi
    min:
      cpu: 13m
      memory: 5Mi
    max:
      cpu: 182m
      memory: 20Mi
