apiVersion: v1
kind: LimitRange
metadata:
  name: staging-limits
  namespace: staging
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 20m
      memory: 6Mi
    default:
      cpu: 100m
      memory: 20Mi
    min:
      cpu: 12m
      memory: 5Mi
    max:
      cpu: 200m
      memory: 24Mi
