apiVersion: v1
kind: LimitRange
metadata:
  name: tools-limits
  namespace: tools
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 20m
      memory: 6Mi
    default:
      cpu: 100m
      memory: 20Mi
    min:
      cpu: 10m
      memory: 4Mi
    max:
      cpu: 500m
      memory: 512Mi
